[package]
name = "pc_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
eframe = "0.30.0"
env_logger = "0.11.6"
log = "0.4.25"
rfd = "0.15.2"
rustfft = "6.2.0"
serialport = "4.7.0"
