[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash --baud 1500000 --monitor --partition-table ./partitions.csv"
rustflags = ["--cfg", "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
#ESP_IDF_VERSION = "v5.4"
#CRATE_CC_NO_DEFAULTS="1"

